#
#  Author: Hari Sekhon
#  Date: 2024-06-21 17:39:15 +0200 (Fri, 21 Jun 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Terraform
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   T F l i n t   G i t H u b   W o r k f l o w
# ============================================================================ #

---
name: tflint

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  #schedule:
  #  - cron: '30 0 * * 1'

jobs:
  tfsec:
    name: tfsec
    uses: HariSekhon/GitHub-Actions/.github/workflows/tflint.yaml@master
    permissions:
      contents: read
