#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Terraform
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#


# ============================================================================ #
#                   T F s e c   G i t H u b   W o r k f l o w
# ============================================================================ #

# Comments on any PR that adds transgressions

# https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/github-actions/pr-commenter/

---
name: tfsec-pr-commenter

on:
  pull_request:

jobs:
  tfsec_pr_commenter:
    name: tfsec PR commenter
    uses: HariSekhon/GitHub-Actions/.github/workflows/tfsec-pr-commenter.yaml@master
