#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Terraform
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   T F s e c   G i t H u b   W o r k f l o w
# ============================================================================ #

# Static analysis of Terraform code - publishes report to GitHub Security tab

# https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/github-actions/github-action/

---
name: tfsec

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  #schedule:
  #  - cron: '30 0 * * 1'

jobs:
  tfsec:
    name: tfsec
    uses: HariSekhon/GitHub-Actions/.github/workflows/tfsec.yaml@master
    permissions:
      actions: read
      contents: read
      security-events: write
